In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [2]:
## load the trained model, scaler pickle, onehot
model = load_model("model.h5")

WARNING:tensorflow:From c:\Users\n\ANN Classification Project\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [6]:
## load the encoder and the scaler 
with open("onehot_encoder_geo.pkl", "rb") as file:
    label_encoder_geo = pickle.load(file)

with open("label_encoder.pkl", "rb") as file:
    label_encoder_gender = pickle.load(file)


with open("scaler.pkl", "rb") as file:
    scaler = pickle.load(file)

In [8]:
input_data = {
    "CreditScore": 600,
    "Geography": "France",
    "Gender": "Male",
    "Age": 40,
    "Tenure": 3,
    "Balance": 60000,
    "NumOfProducts": 2,
    "HasCrCard": 1,
    "IsActiveMember": 1, 
    "EstimatedSalary": 50000
}

In [10]:
# One-hot encode "Geography"
geo_encoded = label_encoder_geo.transform([[input_data["Geography"]]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(["Geography"]))

c:\Users\n\ANN Classification Project\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [11]:
# One-hot encode "Geography"
# Remove .toarray() because the output is already a dense array
geo_encoded = label_encoder_geo.transform([[input_data["Geography"]]])

# Now create the DataFrame
geo_encoded_df = pd.DataFrame(
    geo_encoded, 
    columns=label_encoder_geo.get_feature_names_out(["Geography"])
)

c:\Users\n\ANN Classification Project\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [12]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [14]:
input_df = pd.DataFrame([input_data])
input_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [15]:
# Encode my categorical variables
input_df["Gender"]=label_encoder_gender.transform(input_df["Gender"])
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [17]:
# concatination one hot encoded data
input_df = pd.concat([input_df.drop("Geography", axis=1), geo_encoded_df], axis=1)

In [18]:
input_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [19]:
## Scaling the input data
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [20]:
# Predict the churn
prediction = model.predict(input_scaled)

1/1 [==============================] - 0s 248ms/step

In [22]:
prediction

array([[0.18061334]], dtype=float32)

In [23]:
prediction_proba = prediction[0][0]

In [24]:
prediction_proba

0.18061334